### ISSUE TITLE
Question about computation time

### ISSUE THREAD

**Issue by trofimovaolga** [snu-mllab/Efficient-Dataset-Condensation#1]
Hi, could you please tell how long does it take to condense ImageNet subset?

**Comment by Janghyun1230** [comment]
Hello, with a single GPU (rtx3090) on ImageNet-10, it takes about 8 hours to obtain data that have the best neural net training performance. (in current codes, I set large number of optimization iterations to check the convergence)

The complexity of codes is linear to the number of classes, so I recommand to use multi-processing on ImageNet-100.
