### ISSUE TITLE
The frequency of testing the condensed data

### ISSUE THREAD

**Issue by HiccupRL** [snu-mllab/Efficient-Dataset-Condensation#2]
In your code, you just use `it_test = [n_iter // 10, n_iter // 5, n_iter // 2, n_iter]` to evaluate the test accuracy of condensed data. However, when I rerun your code, I didn't get ideal result that described in your paper? So will you use more frequent evaluation in your training. And will you calculate this evaluation time in your table?

Thank you very much for your sincere answer.

**Comment by Janghyun1230** [comment]
Hello, the evaluation time mentioned in Table 2 of the paper refers to the time taken to train the model using the condensed data, not the time taken for the condensation. You can verify the evaluation time with the test.py.

Also, you can check the log and results of the dataset condensation process here: https://drive.google.com/drive/folders/1yh0Hf2ia4b-1edMiAr1kXCH4eUcYNfmz.
