### ISSUE TITLE
Can you share the download link for the Imagenet10 and imagenet100

### ISSUE THREAD

**Issue by HiccupRL** [snu-mllab/Efficient-Dataset-Condensation#3]
Hello, I want to reproduce your result on `Imagenet10` and `imagenet100`. However there is a question for that there are so many kind of `Imagenet10` and `imagenet100`. So can you please give us a official link to get the `Imagenet10` and `imagenet100`, which is the same as yours.
Thank you  for your sincere help.

**Comment by Janghyun1230** [comment]
Hello! The class list for ImageNet10 and 100 can be found in `./misc/class100.txt` in this repository (where ImageNet10 uses the first 10 classes). Note that the file is loaded at `data.py L92-105`.

**Comment by HiccupRL** [comment]
Yeah, got it. Thank you. 
So I simply put the full `imagenet` in the data diretory, the class list will automatically load class100.
