### ISSUE TITLE
`python condense_mp.py --reproduce  -d imagenet --nclass 100 --pt_from 5 -f [factor] --ipc [image/class] --nclass_sub 20 --phase [0,1,2,3,4]`

### ISSUE THREAD

**Issue by HiccupRL** [snu-mllab/Efficient-Dataset-Condensation#5]
Hello, Thanks for your solid work.
When I want to reproduce your code in `imagenet100 ipc=20`, I use the command of ` python condense_mp.py --reproduce -d imagenet --nclass 100 --pt_from 5 -f 1 --ipc 10 --nclass_sub 20 --phase 5`, I found that there are some error in running it.
So how many GPUs did you use in your experiment, and how long will it take?

**Comment by Janghyun1230** [comment]
The command uses a pertained network trained with five epochs (--pt_from). 

To use this command, you should first obtain pretrained networks by run 
```python pretrain.py -d imagenet --nclass 100 -n resnet_ap --pt_from [pretrain epochs] --seed [seed]```

I've also uploaded the pretrained networks at https://drive.google.com/drive/folders/1YdBOf_u41bTtHyEWxzoqwzMagCrT-Y1H?usp=drive_link , so you can just download the networks and use them. (Note the number tag in the file names represents the epochs trained)

As I recall, each run used one RTX-3090 GPU (23GB memory). You can also check run times for each experiment at log files from Data folders: https://drive.google.com/drive/folders/19f82htg2AiXlqw7Si9QdUsnuXJrbTeyt .

**Comment by HiccupRL** [comment]
OK，got it. Thanks for your sincere help!

**Comment by HiccupRL** [comment]
![image](https://github.com/snu-mllab/Efficient-Dataset-Condensation/assets/100175107/c351f1b1-c684-452e-ae06-2b7043d2349e)
Following your instruction that use `pretrain.py`, the experiment still seems to stuck. Our GPU is V100(32GB), so maybe there are some details I mistake, for that the memory is enough and no error or warning raised.
Thank for your sincere help.

**Comment by HiccupRL** [comment]
Fixed it. There are something wrong in my computer. Thank you!
